<?php
	class ServiceCode {
		var $BOOKNLIFE_COUPON                             = "0100" ; // 도서상품권
		var $CULTURELAND_COUPON                           = "0200" ; // 문화상품권
		var $GAME_CULTURE_COUPON                          = "0300" ; // 게임문화상품권
		var $HAPPYMONEY_COUPON                            = "0500" ; // 해피머니상품권
		var $CASHGATE                                     = "0700" ; // 편의점
		var $ARS700                                       = "0800" ; // ARS700
		var $CREDIT_CARD                                  = "0900" ; // 신용카드
		var $ACCOUNT_TRANSFER                             = "1000" ; // 계좌이체
		var $MOBILE                                       = "1100" ; // 휴대폰
		var $PHONEBILL                                    = "1200" ; // 폰빌
		var $CASH_RECEIPT                                 = "1500" ; // 현금영수증
		var $T_MONEY                                      = "1600" ; // 티머니
		var $VIRTUAL_ACCOUNT                              = "1800" ; // 가상계좌
		var $TEEN_CASH                                    = "2500" ; // 틴캐시
		var $EGGMONEY_COUPON                              = "2600" ; // 에그머니
		var $MONEY_TREE                                   = "4100" ; // 머니트리
	}

	class Command {
		var $VIRTUAL_ACCOUNT_REGIST_REQUEST               = "0100"; // 가상계좌 등록 요청
		var $VIRTUAL_ACCOUNT_REGIST_RESPONSE              = "0101"; // 가상계좌 등록 응답
		var $DEMAND_REGIST_REQUEST                        = "0200"; // 청구데이터 등록 요청
		var $DEMAND_REGIST_RESPONSE                       = "0201"; // 청구데이터 등록 응답
		var $DEMAND_REGIST_WITH_ACCOUNT_REQUEST           = "0210"; // 청구데이터  가상계좌지정 등록 요청
		var $DEMAND_REGIST_WITH_ACCOUNT_RESPONSE          = "0211"; // 청구데이터  가상계좌지정 등록  응답
		var $DEMAND_REGIST_AND_ACCOUNT_REGIST_REQUEST     = "0220"; // 청구데이터  등록 및 가상계좌 등록 요청
		var $DEMAND_REGIST_AND_ACCOUNT_REGIST_RESPONSE    = "0221"; // 청구데이터 등록 및 가상계좌 등록  응답
		var $DEMAND_REGIST_WITH_DEMAND_GROUP_REQUEST      = "0230"; // 청구데이터  등록 [청구그룹별 등록] 요청
		var $DEMAND_REGIST_WITH_DEMAND_GROUP_RESPONSE     = "0231"; // 청구데이터 등록 [청구그룹별 등록] 응답
		var $TEST_CALL_REQUEST                            = "0300"; // 테스트콜 요청
		var $TEST_CALL_RESPONSE                           = "0301"; // 테스트콜 응답
		var $INQUIRY_REQUEST                              = "1000"; // 조회 요청
		var $INQUIRY_RESPONSE                             = "1001"; // 조회 응답
		var $PIN_INQUIRY_REQUEST                          = "1010"; // 핀 조회 요청
		var $PIN_INQUIRY_RESPONSE                         = "1011"; // 핀 조회 응답
		var $ACCOUNT_PAYMENT_INQUIRY_REQUEST              = "1100"; // 가상계좌 수납여부 조회 요청
		var $ACCOUNT_PAYMENT_INQUIRY_RESPONSE             = "1101"; // 가상계좌 수납여부 조회  응답
		var $ID_INQUIRY_REQUEST                           = "1020"; // ID 조회 요청
		var $ID_INQUIRY_RESPONSE                          = "1021"; // ID 조회 응답
		var $CERTIFY_REQUEST                              = "2000"; // 인증 요청
		var $CERTIFY_RESPONSE                             = "2001"; // 인증 응답
		var $AUTO_BILL_CERTIFY_REQUEST                    = "2100"; // 자동과금 인증 요청
		var $AUTO_BILL_CERTIFY_RESPONSE                   = "2101"; // 자동과금 인증 요청 응답
		var $IDENTITY_CERTIFY_REQUEST                     = "2110"; // 본인인증 요청
		var $IDENTITY_CERTIFY_RESPONSE                    = "2111"; // 본인인증  요청  응답
		var $AUTO_BILL_AGREE_CERTIFY_REQUEST              = "2120"; // 자동과금  동의 인증 요청
		var $AUTO_BILL_AGREE_CERTIFY_RESPONSE             = "2121"; // 자동과금 동의 인증  요청  응답
		var $ID_CERTIFY_REQUEST                           = "2010"; // ID 인증 요청
		var $ID_CERTIFY_RESPONSE                          = "2011"; // ID 인증 응답
		var $CERTIFY_SMS_REQUEST                          = "2200"; // 인증 SMS 재 전송 요청
		var $CERTIFY_SMS_RESPONSE                         = "2201"; // 인증 SMS 재 전송 요청 응답
		var $ARS_CERTIFY_REQUEST                          = "2300"; // ARS데몬 인증 요청
		var $ARS_CERTIFY_RESPONSE                         = "2301"; // ARS데몬 인증 요청 응답
		var $AUTH_REQUEST                                 = "3000"; // 승인 요청
		var $AUTH_RESPONSE                                = "3001"; // 승인 응답 
		var $ID_AUTH_REQUEST                              = "3010"; // ID 승인 요청
		var $ID_AUTH_RESPONSE                             = "3011"; // ID 승인 응답
		var $AUTO_BILL_AUTH_REQUEST                       = "3020"; // 자동과금 승인 요청
		var $AUTO_BILL_AUTH_RESPONSE                      = "3021"; // 자동과금 승인 응답
		var $AUTO_BILL_AGREE_AUTH_REQUEST                 = "3030"; // 자동 과금  동의 승인 요청
		var $AUTO_BILL_AGREE_AUTH_RESPONSE                = "3031"; // 자동 과금 동의 승인 응답
		var $CERTIFY_AUTH_REQUEST                         = "3040"; // 인증 및 승인 요청
		var $CERTIFY_AUTH_RESPONSE                        = "3041"; // 인증 및 승인 응
		var $ID_CERTIFY_AUTH_REQUEST                      = "3050"; // 아이디  인증/승인 요청
		var $ID_CERTIFY_AUTH_RESPONSE                     = "3051"; // 아이디 인증/승인 응답
		var $PIN_CERTIFY_AUTH_REQUEST                     = "3060"; // 핀 인증/승인 요청
		var $PIN_CERTIFY_AUTH_RESPONSE                    = "3061"; // 핀 인증/승인 응
		var $IDENTITY_CONFIRM_REQUEST                     = "3110"; // 본인인증 확인 요청
		var $IDENTITY_CONFIRM_RESPONSE                    = "3111"; // 본인인증  확인 요청  응답
		var $BILL_REQUEST                                 = "3900"; // 최종 과금 요청
		var $BILL_RESPONSE                                = "3901"; // 최종 과금 응답
		var $AUTO_BILL_AGREE_BILL_REQUEST                 = "3910"; // 자동 과금  동의 과금 요청
		var $AUTO_BILL_AGREE_BILL_RESPONSE                = "3911"; // 자동 과금 동의 과금 응답
		var $ALARM_REQUEST                                = "4000"; // 알람 요청 
		var $ALARM_RESPONSE                               = "4001"; // 알람 요청 응답
		var $AUTH_MAIL_REQUEST                            = "4010"; // 승인 메일 요청
		var $AUTH_MAIL_RESPONSE                           = "4011"; // 승인 메일 요청 응답
		var $AUTH_QUERY_REQUEST                           = "5000"; // 승인 내역 조회 요청
		var $AUTH_QUERY_RESPONSE                          = "5001"; // 승인 내역 조회 응답
		var $CERTIFY_QUERY_REQUEST                        = "5100"; // 인증 결과 확인 요청
		var $CERTIFY_QUERY_RESPONSE                       = "5101"; // 인증 결과 확인 요청 응답
		var $SUM_QUERY_REQUEST                            = "5200"; // 집계 결과 확인 요청
		var $SUM_QUERY_RESPONSE                           = "5201"; // 집계 결과 확인 요청 응답
		var $JOB_START_REQUEST                            = "6100"; // 업무개시 요청
		var $JOB_START_RESPONSE                           = "6101"; // 업무개시 응답
		var $JOB_END_REQUEST                              = "6200"; // 업무종료 요청
		var $JOB_END_RESPONSE                             = "6201"; // 업무종료 응답
		var $DEMAND_UPDATE_REQUEST                        = "8000"; // 청구데이터  수정 요청
		var $DEMAND_UPDATE_RESPONSE                       = "8001"; // 청구데이터  수정  응답
		var $VIRTUAL_ACCOUNT_UPDATE_REQUEST               = "8010"; // 가상계좌  수정 요청
		var $VIRTUAL_ACCOUNT_UPDATE_RESPONSE              = "8011"; // 가상계좌  수정  응답
		var $REFUND_SMS_REQUEST                           = "8100"; // 환불 SMS 요청
		var $REFUND_SMS_RESPONSE                          = "8101"; // 환불 SMS 응답
		var $CANCEL_REQUEST                               = "9000"; // 취소 요청
		var $CANCEL_RESPONSE                              = "9001"; // 취소 응답
		var $CANCEL_ADMIN_REQUEST                         = "9010"; // 취소 요청 [관리자용]
		var $CANCEL_ADMIN_RESPONSE                        = "9011"; // 취소 응답 [관리자용]
		var $NETWORK_CANCEL_REQUEST                       = "9100"; // 망 취소 요청
		var $NETWORK_CANCEL_RESPONSE                      = "9101"; // 망 취소 응답
		var $CANCEL_SMS_REQUEST                           = "9200"; // SMS 취소 요청
		var $CANCEL_SMS_RESPONSE                          = "9201"; // SMS 취소 응답
		var $BUY_CANCEL_REQUEST                           = "9300"; // 매입 취소 요청
		var $BUY_CANCEL_RESPONSE                          = "9301"; // 매입 취소 응답 
		var $CASHRECEIPT_REQUEST                          = "3200"; // 현금영수증 데이터등록 요청
		var $CASHRECEIPT_RESPONSE                         = "3201"; // 현금영수증 데이터등록 요청 응답
		var $CASHRECEIPT_BATCH_REQUEST                    = "3210"; // 현금영수증 데이터 파일 등록 요청
		var $CASHRECEIPT_BATCH_RESPONSE                   = "3211"; // 현금영수증 데이터  파일 등록 요청  응답
		var $CASHRECEIPT_RESULT_REQUEST                   = "3220"; // 현금영수증 처리결과 데이터 파일 요청
		var $CASHRECEIPT_RESULT_RESPONSE                  = "3221"; // 현금영수증 처리결과 데이터 파일 요청 응답
		var $EASY_AUTH_REQUEST                            = "3600"; // 승인 요청
		var $EASY_AUTH_RESPONSE                           = "3601"; // 승인 응답
	}

	class MessageTag {
		var $USER_ID                                      = "0001" ; // 고객 ID
		var $USER_NAME                                    = "0002" ; // 고객 이름
		var $ITEM_CODE                                    = "0003" ; // 상품 코드
		var $ITEM_NAME                                    = "0004" ; // 상품 이름
		var $USER_IP                                      = "0005" ; // 고객 IP
		var $USER_EMAIL                                   = "0006" ; // 고객 Email
		var $MOBILE_NUMBER                                = "0007" ; // 휴대폰 번호
		var $PIN_NUMBER                                   = "0008" ; // 핀 번호
		var $PASSWORD                                     = "0009" ; // 패스워드
		var $BUSINESS_NUMBER                              = "0010" ; // 사업자 등록 번호
		var $DEAL_DATE                                    = "0011" ; // 거래 일시
		var $DEAL_AMOUNT                                  = "0012" ; // 거래 금액(공급가액)
		var $VAT                                          = "0013" ; // 부가세
		var $SERVICE_CHARGE                               = "0014" ; // 봉사료
		var $USING_TYPE                                   = "0015" ; // 거래자 구분
		var $DEAL_TYPE                                    = "0016" ; // 거래 구분
		var $IDENTIFIER                                   = "0017" ; // 신분 확인
		var $CASH_ID                                      = "0018" ; // 캐쉬 ID
		var $CASH_PASSWORD                                = "0019" ; // 캐쉬 패스워드
		var $PIN_PASSWORD                                 = "0020" ; // 핀 패스워드
		var $MALL_USER_ID                                 = "0021" ; // 가맹점 고객 ID
		var $AFFILIATER_REGISTER_ID                       = "0022" ; // 제휴사 등록 아이디
		var $ITEM_KIND                                    = "0023" ; // 상품 종류
		var $NOTIFY_TYPE                                  = "0024" ; // 통지 형태
		var $ORDER_ID                                     = "0025" ; // 승인 요청시 주문 번호
		var $TERMINAL_ID                                  = "0026" ; // 터미널 ID
		var $CURRENCY                                     = "0030" ; // 통화 구분
		var $QUOTA                                        = "0031" ; // 할부 개월 수
		var $EXPIRE_DATE                                  = "0032" ; // 유효년일
		var $CVC2                                         = "0033" ; // CVC2
		var $CARD_COMPANY_CODE                            = "0034" ; // 카드사 코드
		var $CERT_TYPE                                    = "0035" ; // ISP/MIP 구분
		var $INTEREST_TYPE                                = "0036" ; // 무이자 할부 구분
		var $MIX_TYPE                                     = "0037" ; // 복합결제 여부
		var $RECEIVER_NAME                                = "0038" ; // 수령자 성명
		var $RECEIVER_ADDRESS                             = "0039" ; // 수령자 배송지
		var $MPI_CAVV                                     = "0040" ; // MPI CAVV
		var $MPI_XID                                      = "0041" ; // MPI X-ID
		var $MPI_ECI                                      = "0042" ; // MPI EC-I
		var $SESSION_KEY                                  = "0043" ; // SessionKey
		var $ENCRYPT_DATA                                 = "0044" ; // Encrypted Data
		var $IC_DATA_TYPE                                 = "0045" ; // IC DATA 형태
		var $IC_DATA                                      = "0046" ; // IC DATA
		var $SIGN_TYPE                                    = "0047" ; // 서명유무
		var $SIGN_DATA                                    = "0048" ; // Sign DATA
		var $ANI                                          = "0049" ; // ANI
		var $DNIS                                         = "0050" ; // DNIS
		var $WIRE_NUMBER                                  = "0051" ; // 유선번호
		var $AGREE_MONTHS                                 = "0052" ; // 동의기간
		var $SEARCH_START_DATE                            = "0053" ; // 검색 시작일자
		var $SEARCH_END_DATE                              = "0054" ; // 검색 끝일자
		var $FILE_NAME                                    = "0055" ; // 파일명
		var $FILE_SIZE                                    = "0056" ; // 파일 크기
		var $FILE_DATA                                    = "0057" ; // 파일 데이타
		var $FILE_SEQ                                     = "0058" ; // 파일 Sequence

		var $MOBILE_COMPANY_CODE                          = "0059" ; // 이동통신사 코드
		var $RESPONSE_RETURN_URL                          = "0060" ; // 정상응답 리턴 URL
		var $RESPONSE_FAIL_URL                            = "0061" ; // 실패응답 리턴URL

		var $BANK_ID                                      = "0062" ; // 은행아이디
		var $ACCOUNT_NAME                                 = "0063" ; // 계좌명
		var $COMPANY_NAME                                 = "0064" ; // 이용기관명
		var $REFUND_FLAG                                  = "0065" ; // 환불 구분값
		var $TRANSFER_FLAG                                = "0066" ; // 거래 구분값
		var $FEE                                          = "0067" ; // 수수료
		var $CPCODE                                       = "0068" ; // CPCODE
		var $SOCIAL_NUMBER                                = "0069" ; // 주민번호
		var $OPCODE                                       = "0070" ; // OPCODE
		var $CRYPTO_SOCIAL_NUMBER                         = "0071" ; // 암호화값
		var $CRYPTO_ANI                                   = "0072" ; // 암호화값
		var $CRYPTO_CASH_ID                               = "0073" ; // 암호화값
		var $AFFILIATER_CODE                              = "0074" ; // 제휴사 코드
		var $EMAIL_TEMPLATE_CODE                          = "0075" ; // 메일 템플릿 코드
		var $CALL_CENTER_NEMBER                           = "0076" ; // 가맹점 콜센터 전화번호 

		var $BANK_CUSTOMER_CODE                           = "0077" ; // 가맹점 은행 기관코드
		var $STATUS_CODE                                  = "0078" ; // 상태코드
		var $MULTI_BILL_ACCOUNT_CODE                      = "0079" ; // 가상계좌 다계좌 정산코드
		var $ACCOUNT_NUMBER                               = "0080" ; // 가상계좌 번호
		var $ACCOUNT_ID                                   = "0081" ; // 가상계좌 고유번호
		var $REQUIRE_TYPE                                 = "0082" ; // 수납필수여부 

		var $ADSL_ID                                      = "0083" ; // 메가패스 ID
		var $ADSL_BALANCE                                 = "0084" ; // ADSL 잔액
		var $ARS_BALANCE                                  = "0085" ; // ARS 잔액
		var $ARS_AUTH_AMOUNT                              = "0086" ; // ARS 결제 금액
		var $ADSL_AUTH_AMOUNT                             = "0087" ; // ADSL 결제 금액
		var $MAX_DATE                                     = "0088" ; // MAX DATE
		var $NOW_DATE                                     = "0089" ; // NOW DATE
		var $RANDOM_CERT_NUMBER                           = "0090" ; // 랜덤 인증 번호
		var $SERVICE_TYPE                                 = "0091" ; // 서비스타입
		var $SERVICE_TYPE_DETAIL                          = "0092" ; // 서비스타입 상세

		var $BANK_CODE                                    = "0093" ; // 은행코드
		var $PROCESS_DATE                                 = "0094" ; // 처리일자
		var $CPCODE_PASSWORD                              = "0095" ; // CPCODE 패스워드
		var $PROTOCOL_NUMBER                              = "0096" ; // 전문번호
		var $PRE_PROTOCOL_NUMBER                          = "0097" ; // 이전 전문번호
		var $TRANSFER_DATE                                = "0098" ; // 전송일자
		var $TRANSFER_TIME                                = "0099" ; // 전송시간
		var $SERVICE_KIND_CODE                            = "0100" ; // 서비스 구분 코드
		var $SERVICE_TRANSACTION_ID                       = "0101" ; // 서비스 TRANSACTION ID
		var $IDENTIFIER_TYPE                              = "0102" ; // 신분확인 값 구분 코드 (01: 주민번호, 02:휴대폰, 03: 현금영수증카드번호, 04:사업자번호)
		var $PRE_TRANSFER_DATE                            = "0103" ; // 이전 전송일자
		var $AGENT_NAME                                   = "0104" ; // 가맹점 명

		var $INPUT_BANK_CODE                              = "0105" ; // 입금 은행코드 
		var $INPUT_ACCOUNT_NUMBER                         = "0106" ; // 입금 계좌번호
		var $INPUT_ACCOUNT_NAME                           = "0107" ; // 입금 계좌 예금주명
		var $INPUT_ACCOUNT_PASSWORD                       = "0108" ; // 입금 계좌 비밀번호
		var $OUTPUT_BANK_CODE                             = "0109" ; // 출금 은행코드 
		var $OUTPUT_ACCOUNT_NUMBER                        = "0110" ; // 출금 계좌번호
		var $OUTPUT_ACCOUNT_NAME                          = "0111" ; // 출금 계좌 예금주명
		var $OUTPUT_ACCOUNT_PASSWORD                      = "0112" ; // 출금 계좌 비밀번호
		var $OUTPUT_ACCOUNT_SOCIAL_NUMBER                 = "0113" ; // 출금 계좌 계좌실명번호
		var $INPUT_ACCOUNT_PRINT                          = "0114" ; // 입금 계좌 인자
		var $OUTPUT_ACCOUNT_PRINT                         = "0115" ; // 출금 계좌 인자

		var $TRANSACTION_ID                               = "1001" ; // 거래 번호
		var $RESPONSE_CODE                                = "1002" ; // 응답 코드
		var $RESPONSE_MESSAGE                             = "1003" ; // 응답 메시지
		var $AUTH_NUMBER                                  = "1004" ; // 승인 번호
		var $AUTH_DATE                                    = "1005" ; // 승인 일시
		var $BALANCE                                      = "1006" ; // 잔액
		var $AUTH_AMOUNT                                  = "1007" ; // 결제 금액
		var $CANCEL_DATE                                  = "1008" ; // 취소 일시
		var $DETAIL_RESPONSE_CODE                         = "1009" ; // 상세 응답 코드
		var $DETAIL_RESPONSE_MESSAGE                      = "1010" ; // 상세 응답 메시지
		var $REQUEST_DATE                                 = "1011" ; // 거래 요청 일자
		var $PRE_TRANSACTION_ID                           = "1012" ; // 이전 거래 번호
		var $AFFILIATER_RESPONSE_CODE                     = "1013" ; // 제휴사 에러코드 
		var $EXPIRATION_DATE                              = "1014" ; // 유효 기간
		var $CARD_TYPE                                    = "1015" ; // 카드 타입(도토리 상품권 : 충전형, 고정형, slip 형, online)
		var $ISSUE_DATE                                   = "1016" ; // 발행 일자
		var $CERT_NUMBER                                  = "1017" ; // 인증 번호
		var $USER_KEY                                     = "1018" ; // 사용자 키
		var $AFFILIATER_TRANSACTION_ID                    = "1019" ; // 제휴사 거래 번호
		var $AGENT_NUMBER                                 = "1020" ; // 가맹점 번호
		var $ISSUE_COMPANY_CODE                           = "1021" ; // 카드발급사코드
		var $BUY_COMPANY_CODE                             = "1022" ; // 카드매입사코드
		var $CANCEL_REASON_TYPE                           = "0204" ; // 취소사유

		var $RESULT                                       = "1023" ; // result
		var $ERROR_CODE                                   = "1024" ; // errorCode
		var $CALLER_ID                                    = "1025" ; // caller_id
		var $SERVICE_ID                                   = "1026" ; // service_id
		var $ID_BALANCE                                   = "1027" ; // 아이디 잔액

		var $TRANSFER_COUNT                               = "1028" ; // 이체건수
		var $TRANSFER_AMOUNT                              = "1029" ; // 이체금액
		var $REFUND_COUNT                                 = "1030" ; // 지급이체건수
		var $REFUND_AMOUNT                                = "1031" ; // 지급이체금액

		var $RESERVED01                                   = "9001" ; // 임시 필드
		var $RESERVED02                                   = "9002" ; // 임시 필드
		var $RESERVED03                                   = "9003" ; // 임시 필드	
	}
?>